# A sample Gemfile
source "https://rubygems.org"

gem "rails", '~> 2.2.3'

gem 'mysql2'
gem 'activerecord-mysql2-adapter'

group :development, :test do
  gem 'rdoc', '~> 2.4.2'
  gem 'rake', '>= 0.9.2.2'
end
