#!/bin/sh
APPDIR=`dirname $0`;
java  -cp "$APPDIR/src:$APPDIR/bin:/home/ccaroon/src/gwt-linux-1.2.22/gwt-user.jar:/home/ccaroon/src/gwt-linux-1.2.22/gwt-dev-linux.jar" com.google.gwt.dev.GWTShell -out "$APPDIR/www" "$@" org.caroon.Sudoku/Sudoku.html;
